name: Build baota-docker Image
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  push:
    tags:
      - "v*"

jobs:
  Baota-docker_clear_image_Build:
    name: Build baota-docker Image (clear)
    runs-on: ubuntu-latest
    steps:
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} # ${{ steps.get_version.outputs.VERSION }}
      -
        name: Private Actions Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: clear/
          platforms: linux/amd64
          file: clear/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baota-docker:clear
        continue-on-error: true

  Baota-docker_ln_image_Build:
    name: Build baota-docker Image (ln)
    runs-on: ubuntu-latest
    steps:
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} # ${{ steps.get_version.outputs.VERSION }}
      -
        name: Private Actions Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: ln/
          platforms: linux/amd64
          file: ln/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baota-docker:ln
        continue-on-error: true

  Baota-docker_lnp_image_Build:
    name: Build baota-docker Image (lnp)
    runs-on: ubuntu-latest
    steps:
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} # ${{ steps.get_version.outputs.VERSION }}
      -
        name: Private Actions Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: lnp/
          platforms: linux/amd64
          file: lnp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baota-docker:lnp
        continue-on-error: true

  Baota-docker_lnmp_image_Build:
    name: Build baota-docker Image (lnmp)
    runs-on: ubuntu-latest
    steps:
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} # ${{ steps.get_version.outputs.VERSION }}
      -
        name: Private Actions Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      -
        name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: true
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: lnmp/
          platforms: linux/amd64
          file: lnmp/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baota-docker:lnmp
        continue-on-error: true
